// Code generated by wit-bindgen-go. DO NOT EDIT.

package example

// Exports represents the caller-defined exports from "component:hello-world/example".
var Exports struct {
	// Greet represents the caller-defined, exported function "greet".
	//
	//	greet: func(greetee: string) -> string
	Greet func(greetee string) (result string)
}
