// Code generated by wit-bindgen-go. DO NOT EDIT.

package example

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "component:hello-world".

//go:wasmexport greet
//export greet
func wasmexport_Greet(greetee0 *uint8, greetee1 uint32) (result *string) {
	greetee := cm.LiftString[string]((*uint8)(greetee0), (uint32)(greetee1))
	result_ := Exports.Greet(greetee)
	result = &result_
	return
}
