// Code generated by wit-bindgen-go. DO NOT EDIT.

package additionalgreeting

// This file contains wasmimport and wasmexport declarations for "local:additional-greeting".

//go:wasmexport additional-greeting
//export additional-greeting
func wasmexport_AdditionalGreeting() (result *string) {
	result_ := Exports.AdditionalGreeting()
	result = &result_
	return
}
