// Code generated by wit-bindgen-go. DO NOT EDIT.

package additionalgreeting

// Exports represents the caller-defined exports from "local:additional-greeting/additional-greeting".
var Exports struct {
	// AdditionalGreeting represents the caller-defined, exported function "additional-greeting".
	//
	//	additional-greeting: func() -> string
	AdditionalGreeting func() (result string)
}
